# Generated by Django 3.2.6 on 2021-09-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre_transporte', models.CharField(max_length=128)),
                ('ruta', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Bus',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128)),
                ('hora_apertura', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_cierra', models.TimeField(verbose_name='Hora de Finalización')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_terminal', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_terminal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Terminales',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.TextField()),
                ('foto', models.ImageField(upload_to='taxi')),
                ('placa', models.CharField(max_length=16)),
                ('ubicacion', models.TextField()),
                ('descripcion', models.TextField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_taxi', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_taxi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Taxis',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='HorarioBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('origen', models.CharField(max_length=128)),
                ('destino', models.CharField(max_length=128)),
                ('hora_salida', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_llegada', models.TimeField(verbose_name='Hora de Finalización')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.bus')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_horariobus', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_horariobus', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Horarios',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transportes.terminal'),
        ),
        migrations.AddField(
            model_name='bus',
            name='usuario_grabacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_bus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_bus', to=settings.AUTH_USER_MODEL),
        ),
    ]
