# Generated by Django 3.2.6 on 2021-09-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('foto', models.ImageField(upload_to='usuarios')),
                ('cedula', models.CharField(blank=True, max_length=16, null=True)),
                ('carnet', models.CharField(blank=True, max_length=16, null=True)),
                ('telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('sexo', models.IntegerField(choices=[(1, 'Hombre'), (1, 'Mujer')])),
                ('fecha_nacimiento', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_perfil', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
