# Generated by Django 3.2.6 on 2021-09-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('descripcion', models.TextField(max_length='900', verbose_name='Descripcion')),
                ('foto', models.ImageField(upload_to='habitacion')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_comida', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_comida', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comida',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombres', models.CharField(max_length=128)),
                ('apellidos', models.CharField(max_length=128)),
                ('correo', models.EmailField(max_length=254)),
                ('cedula', models.CharField(max_length=16)),
                ('direccion', models.TextField()),
                ('tipo', models.IntegerField(choices=[(1, 'Uno'), (1, 'Dos')])),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.municipio')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_propietario', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_propietario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Propietarios',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='menu')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.propietario')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_menu', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_menu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Menu',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('ubicacion', models.TextField(max_length='900', verbose_name='Ubicación')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio')),
                ('servicios', models.TextField(max_length='256', verbose_name='Servicios')),
                ('otros_servicios', models.TextField(max_length='900', verbose_name='Otros servicios')),
                ('normas', models.TextField(max_length='256', verbose_name='Normas')),
                ('reglas', models.TextField(max_length='256', verbose_name='Reglas')),
                ('foto', models.ImageField(upload_to='habitacion')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.propietario')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_habitacion', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_habitacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['-fecha_grabacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_grabacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre')),
                ('foto', models.ImageField(upload_to='menu')),
                ('comida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.comida')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='negocios.menu')),
                ('usuario_grabacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_grabacion_detallemenu', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_detallemenu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Detalle Menu',
                'ordering': ['-fecha_grabacion'],
            },
        ),
    ]
