# Generated by Django 3.2.6 on 2021-09-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='servicios',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='agua_potable',
            field=models.BooleanField(default=False, verbose_name='Agua potable'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='comida',
            field=models.BooleanField(default=False, verbose_name='Comida'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='energia_electrica',
            field=models.BooleanField(default=False, verbose_name='Energía eléctrica'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Internet'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='foto',
            field=models.URLField(verbose_name='Foto 360'),
        ),
    ]
