# Generated by Django 3.2.6 on 2021-09-19 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocios', '0003_auto_20210918_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='agua_potable',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='comida',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='energia_electrica',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='internet',
        ),
    ]
